self.__BUILD_MANIFEST = function ({
  e,
  s,
  t,
  a,
  c,
  d,
  i,
  o,
  n,
  r,
  b,
  u,
  h,
  p,
  g,
  f,
  k,
  l,
  j,
  I,
  m,
  x,
  w,
  B,
  Y,
  _,
  G,
  v,
  S,
  y,
  A,
  M,
  T,
  F,
  N,
  C,
  D,
  P,
  L,
  U,
  W,
  E,
  V,
  z,
  R,
  O,
  H,
  J,
  q,
  Z,
  $,
  K,
  Q,
  X,
  ee,
  es
}) {
  return {
    __rewrites: {
      afterFiles: [],
      beforeFiles: [
        { has: L, source: "/embed/:docId*", destination: "/public/:docId*" },
        { has: L, source: "/templates/([\\w-]*-|):id(\\w+)", destination: "/templates/:id" },
        { has: L, source: "/folders/:channelSlug*", destination: "$" },
        { has: L, source: "/settings/:slug*", destination: K },
        { has: L, source: "/sites/:siteId/pages/:pageId/preview", destination: "/sites/:siteId/pages/:pageId" },
        { has: L, source: "/docs/:docId/preview", destination: "/docs/:docId" },
        {
          has: [
            { type: "header", key: "user-agent", value: "(.*)(Googlebot\\/|Googlebot-Mobile|Googlebot-Image|Googlebot-News|Googlebot-Video|AdsBot-Google([^-]|$)|AdsBot-Google-Mobile|Feedfetcher-Google|Mediapartners-Google|Mediapartners \\(Googlebot\\)|APIs-Google|bingbot|Slurp|LinkedInBot|msnbot|Adidxbot|facebookexternalhit|DuckDuckBot|Twitterbot|Facebot|BUbiNG|Applebot|Y!J|Slack-ImgProxy|SkypeUriPreview|Slackbot|Google-Adwords-Instant|WhatsApp|BingPreview\\/|Yahoo Link Preview|AppInsights|Discordbot|DuckDuckGo-Favicons-Bot|AppEngine-Google|Google Web Preview|google-xrawler|Google-Structured-Data-Testing-Tool|Google-PhysicalWeb|Google Favicon|Chrome-Lighthouse|HeadlessChrome|Google-Site-Verification|Google-Certificates-Bridge|Iframely|[wW]get|Python-urllib|python-requests|aiohttp|httpx|libwww-perl|httpunit|nutch|Go-http-client|phpcrawl|jyxobot|FAST-WebCrawler|FAST Enterprise Crawler|BIGLOTRON|Teoma|convera|seekbot|Gigabot|Gigablast|exabot|ia_archiver|GingerCrawler|webmon |HTTrack|grub.org|UsineNouvelleCrawler|antibot|netresearchserver|speedy|fluffy|findlink|msrbot|panscient|yacybot|AISearchBot|ips-agent|tagoobot|MJ12bot|woriobot|yanga|buzzbot|mlbot|YandexBot|YandexImages|YandexAccessibilityBot|YandexMobileBot|YandexMetrika|YandexTurbo|YandexImageResizer|YandexVideo|YandexAdNet|YandexBlogs|YandexDirect|YandexFavicons|YaDirectFetcher|YandexForDomain|YandexMarket|YandexMedia|YandexMobileScreenShotBot|YandexNews|YandexOntoDB|YandexPagechecker|YandexPartner|YandexRCA|YandexSearchShop|YandexSitelinks|YandexSpravBot|YandexTracker|YandexVertis|YandexVerticals|YandexWebmaster|YandexScreenshotBot|purebot|Linguee Bot|CyberPatrol|voilabot|Baiduspider|citeseerxbot|spbot|twengabot|postrank|TurnitinBot|scribdbot|page2rss|sitebot|linkdex|ezooms|dotbot|Mail.RU_Bot|discobot|heritrix|findthatfile|europarchive.org|NerdByNature.Bot|sistrix crawler|Ahrefs(Bot|SiteAudit)|fuelbot|CrunchBot|IndeedBot|mappydata|woobot|ZoominfoBot|PrivacyAwareBot|Multiviewbot|SWIMGBot)(.*)"
          },
          source: "/(docs|example|public)/:slug",
          destination: "/docs-robot/:slug"
        },
        { has: L, source: "/:path*.map", destination: Q }
      ],
      fallback: []
    },
    "/": [e, s, t, a, c, o, p, k, l, j, w, B, Y, _, y, W, d, n, b, h, g, I, G, v, M, E, i, r, m, x, S, A, T, u, "static/chunks/pages/index-b20343862420430e.js"],
    "/404": [e, s, t, a, c, o, d, n, b, i, r, u, f, "static/chunks/pages/404-bd2433b72
